import type { Field, Module } from './types';
const f = (
  key: string,
  label: string,
  type: Field['type'] = 'text',
  more: Partial<Field> = {},
): Field => ({ key, label, type, ...more });
const name = f('name', 'نام', 'text', { required: true });
const code = f('code', 'کد', 'text', { required: true });
const date = f('date', 'تاریخ', 'date', { required: true });
const amount = f('amount', 'مبلغ', 'money', { required: true, min: 0 });
const notes = f('notes', 'توضیحات', 'textarea');
const person = f('personId', 'طرف حساب', 'select', { ref: 'people', required: true });
const bank = f('bankId', 'حساب / صندوق', 'select', { ref: 'banks', required: true });
const currency = f('currency', 'ارز', 'select', {
  options: ['تومان', 'ریال', 'دلار', 'یورو', 'درهم'],
  default: 'تومان',
  required: true,
});
const exchangeRate = f('exchangeRate', 'نرخ تبدیل به تومان', 'number', {
  default: 1,
  required: true,
  min: 0.000001,
});
const invoiceFields: Field[] = [
  code,
  person,
  date,
  f('dueDate', 'سررسید', 'date', { required: true }),
  currency,
  exchangeRate,
  f('warehouseId', 'انبار', 'select', { ref: 'warehouses', required: true }),
  f('discount', 'تخفیف کل', 'money', { default: 0, min: 0 }),
  notes,
];
const invoice = (key: string, title: string, singular: string, group: string): Module => ({
  key,
  title,
  singular,
  group,
  icon: 'receipt',
  description: 'مدیریت اسناد، ردیف اقلام و وضعیت تسویه',
  kind: 'invoice',
  fields: invoiceFields,
  status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
});
const transaction = (key: string, title: string, singular: string): Module => ({
  key,
  title,
  singular,
  group: 'خزانه‌داری',
  icon: 'wallet',
  description: 'ثبت و پیگیری جریان وجوه نقد و تراکنش‌های مالی',
  fields: [
    code,
    person,
    date,
    amount,
    currency,
    exchangeRate,
    bank,
    f('invoiceId', 'فاکتور مرتبط', 'select', { ref: key === 'receipts' ? 'sales' : 'purchases' }),
    f('method', 'روش', 'select', {
      options: ['انتقال بانکی', 'نقدی', 'کارت‌خوان'],
      default: 'انتقال بانکی',
    }),
    notes,
  ],
  status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
});
export const modules: Module[] = [
  {
    key: 'people',
    title: 'اشخاص و طرف حساب‌ها',
    singular: 'طرف حساب',
    group: 'اشخاص',
    icon: 'users',
    description: 'ارتباطی منظم با مشتریان، تأمین‌کنندگان و همکاران شما',
    fields: [
      code,
      name,
      f('type', 'نوع شخص', 'select', {
        options: ['مشتری', 'تأمین‌کننده', 'هر دو', 'سایر'],
        default: 'مشتری',
      }),
      f('phone', 'تلفن'),
      f('email', 'ایمیل', 'email'),
      f('nationalId', 'شناسه ملی / کد ملی'),
      f('creditLimit', 'سقف اعتبار', 'money', { min: 0 }),
      f('address', 'نشانی', 'textarea'),
      notes,
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'products',
    title: 'کالاها و خدمات',
    singular: 'کالا یا خدمت',
    group: 'کالا و انبار',
    icon: 'package',
    description: 'فهرست یکپارچهٔ محصولات، خدمات و قیمت‌ها',
    fields: [
      code,
      name,
      f('type', 'نوع', 'select', { options: ['کالا', 'خدمت'], default: 'کالا' }),
      f('category', 'گروه', 'select', {
        options: ['تجهیزات اداری', 'لوازم دیجیتال', 'خدمات', 'مواد اولیه', 'محصول نهایی'],
        default: 'تجهیزات اداری',
      }),
      f('unit', 'واحد', 'select', {
        options: ['عدد', 'بسته', 'کیلوگرم', 'متر', 'ساعت'],
        default: 'عدد',
      }),
      f('price', 'قیمت فروش', 'money', { required: true, min: 0 }),
      f('cost', 'قیمت خرید', 'money', { required: true, min: 0 }),
      f('minStock', 'حداقل موجودی', 'number', { default: 5, min: 0 }),
      notes,
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'warehouses',
    title: 'انبارها',
    singular: 'انبار',
    group: 'کالا و انبار',
    icon: 'warehouse',
    description: 'انبارها، محل نگهداری و مسئولان موجودی',
    fields: [
      code,
      name,
      f('manager', 'مسئول انبار'),
      f('phone', 'تلفن'),
      f('address', 'نشانی', 'textarea'),
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'stock',
    title: 'گردش موجودی',
    singular: 'گردش انبار',
    group: 'کالا و انبار',
    icon: 'arrows',
    description: 'رسید، حواله و انتقال کالا بین انبارها',
    fields: [
      code,
      date,
      f('productId', 'کالا', 'select', { ref: 'products', required: true }),
      f('warehouseId', 'انبار مبدأ', 'select', { ref: 'warehouses', required: true }),
      f('type', 'نوع گردش', 'select', {
        options: ['رسید', 'حواله', 'انتقال'],
        default: 'رسید',
        required: true,
      }),
      f('destinationId', 'انبار مقصد (انتقال)', 'select', { ref: 'warehouses' }),
      f('quantity', 'تعداد', 'number', { required: true, min: 0.001 }),
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  invoice('quotes', 'پیش‌فاکتورها', 'پیش‌فاکتور', 'خرید و فروش'),
  invoice('sales', 'فاکتورهای فروش', 'فاکتور فروش', 'خرید و فروش'),
  invoice('purchases', 'فاکتورهای خرید', 'فاکتور خرید', 'خرید و فروش'),
  invoice('sales-returns', 'برگشت از فروش', 'برگشت از فروش', 'خرید و فروش'),
  invoice('purchase-returns', 'برگشت از خرید', 'برگشت از خرید', 'خرید و فروش'),
  {
    key: 'banks',
    title: 'حساب‌های بانکی و صندوق',
    singular: 'حساب مالی',
    group: 'خزانه‌داری',
    icon: 'landmark',
    description: 'حساب‌های بانکی، صندوق‌ها و ماندهٔ وجوه',
    fields: [
      code,
      name,
      f('type', 'نوع حساب', 'select', { options: ['بانک', 'صندوق', 'تنخواه'], default: 'بانک' }),
      f('accountNumber', 'شماره حساب'),
      f('iban', 'شماره شبا'),
      currency,
      exchangeRate,
      f('openingBalance', 'مانده اولیه', 'money', { default: 0, min: 0 }),
      notes,
    ],
    status: ['فعال', 'غیرفعال'],
  },
  transaction('receipts', 'دریافت‌ها', 'دریافت'),
  transaction('payments', 'پرداخت‌ها', 'پرداخت'),
  {
    key: 'transfers',
    title: 'انتقال وجه',
    singular: 'انتقال وجه',
    group: 'خزانه‌داری',
    icon: 'arrows',
    description: 'جابجایی وجه میان حساب‌های هم‌ارز شرکت',
    fields: [
      code,
      date,
      f('fromBankId', 'حساب مبدأ', 'select', { ref: 'banks', required: true }),
      f('toBankId', 'حساب مقصد', 'select', { ref: 'banks', required: true }),
      amount,
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  {
    key: 'checks',
    title: 'مدیریت چک‌ها',
    singular: 'چک',
    group: 'خزانه‌داری',
    icon: 'check',
    description: 'چک‌های دریافتی و پرداختی، سررسید و وضعیت وصول',
    fields: [
      code,
      person,
      f('type', 'نوع چک', 'select', { options: ['دریافتی', 'پرداختی'], default: 'دریافتی' }),
      date,
      f('dueDate', 'سررسید', 'date', { required: true }),
      amount,
      currency,
      exchangeRate,
      bank,
      f('sayad', 'شناسه صیادی'),
      notes,
    ],
    status: ['در جریان', 'وصول شده', 'برگشت خورده', 'لغو شده'],
  },
  {
    key: 'expenses',
    title: 'هزینه‌ها',
    singular: 'هزینه',
    group: 'حسابداری',
    icon: 'down',
    description: 'ثبت هزینه‌های عملیاتی و پرداخت‌های شرکت',
    fields: [
      code,
      f('name', 'شرح هزینه', 'text', { required: true }),
      date,
      f('category', 'دسته‌بندی', 'select', {
        options: ['اجاره', 'حقوق', 'حمل و نقل', 'تبلیغات', 'خدمات', 'سایر'],
        default: 'خدمات',
      }),
      amount,
      currency,
      exchangeRate,
      bank,
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  {
    key: 'income',
    title: 'سایر درآمدها',
    singular: 'درآمد',
    group: 'حسابداری',
    icon: 'up',
    description: 'درآمدهای خارج از چرخهٔ فروش',
    fields: [
      code,
      f('name', 'شرح درآمد', 'text', { required: true }),
      date,
      amount,
      currency,
      exchangeRate,
      bank,
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  {
    key: 'accounts',
    title: 'کدینگ حساب‌ها',
    singular: 'حساب',
    group: 'حسابداری',
    icon: 'tree',
    description: 'ساختار حساب‌های کل، معین و تفصیلی',
    fields: [
      code,
      name,
      f('type', 'ماهیت', 'select', {
        options: ['دارایی', 'بدهی', 'سرمایه', 'درآمد', 'هزینه'],
        required: true,
        default: 'دارایی',
      }),
      f('level', 'سطح', 'select', { options: ['کل', 'معین', 'تفصیلی'], default: 'معین' }),
      f('parentId', 'حساب والد', 'select', { ref: 'accounts' }),
      notes,
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'journals',
    title: 'اسناد حسابداری',
    singular: 'سند حسابداری',
    group: 'حسابداری',
    icon: 'book',
    description: 'اسناد دوطرفه با کنترل توازن بدهکار و بستانکار',
    fields: [code, date, f('name', 'شرح سند', 'text', { required: true }), notes],
    kind: 'journal',
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  {
    key: 'employees',
    title: 'کارکنان',
    singular: 'کارمند',
    group: 'حقوق و دستمزد',
    icon: 'user',
    description: 'پروندهٔ کارکنان، قراردادها و اطلاعات پرداخت',
    fields: [
      code,
      name,
      f('nationalId', 'کد ملی'),
      f('position', 'سمت'),
      f('department', 'واحد سازمانی'),
      f('startDate', 'شروع همکاری', 'date'),
      f('salary', 'حقوق پایه ماهانه', 'money', { required: true, min: 0 }),
      f('iban', 'شماره شبا'),
      f('phone', 'تلفن'),
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'payroll',
    title: 'لیست حقوق و فیش‌ها',
    singular: 'فیش حقوق',
    group: 'حقوق و دستمزد',
    icon: 'receipt',
    description: 'محاسبهٔ حقوق، مزایا، کسورات و خالص پرداختی',
    fields: [
      code,
      f('employeeId', 'کارمند', 'select', { ref: 'employees', required: true }),
      date,
      f('month', 'ماه', 'select', {
        options: [
          'فروردین',
          'اردیبهشت',
          'خرداد',
          'تیر',
          'مرداد',
          'شهریور',
          'مهر',
          'آبان',
          'آذر',
          'دی',
          'بهمن',
          'اسفند',
        ],
        default: 'شهریور',
      }),
      f('base', 'حقوق پایه', 'money', { required: true, min: 0 }),
      f('benefits', 'مزایا و اضافه‌کاری', 'money', { default: 0, min: 0 }),
      f('insurance', 'بیمه', 'money', { default: 0, min: 0 }),
      f('tax', 'مالیات', 'money', { default: 0, min: 0 }),
      f('deductions', 'سایر کسورات', 'money', { default: 0, min: 0 }),
      bank,
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'پرداخت شده', 'لغو شده'],
  },
  {
    key: 'assets',
    title: 'دارایی‌های ثابت',
    singular: 'دارایی',
    group: 'دارایی ثابت',
    icon: 'building',
    description: 'شناسنامهٔ دارایی، بهای تمام‌شده و ارزش دفتری',
    fields: [
      code,
      name,
      date,
      f('category', 'گروه دارایی', 'select', {
        options: ['تجهیزات', 'ساختمان', 'خودرو', 'اثاثیه'],
        default: 'تجهیزات',
      }),
      f('cost', 'بهای خرید', 'money', { required: true, min: 0 }),
      f('salvage', 'ارزش اسقاط', 'money', { default: 0, min: 0 }),
      f('life', 'عمر مفید (ماه)', 'number', { required: true, default: 60, min: 1 }),
      f('location', 'محل استقرار'),
      notes,
    ],
    status: ['فعال', 'فروخته شده', 'اسقاط شده'],
  },
  {
    key: 'depreciation',
    title: 'استهلاک دارایی‌ها',
    singular: 'محاسبه استهلاک',
    group: 'دارایی ثابت',
    icon: 'down',
    description: 'ثبت استهلاک خط مستقیم برای دوره‌های ماهانه',
    fields: [
      code,
      f('assetId', 'دارایی', 'select', { ref: 'assets', required: true }),
      date,
      f('months', 'تعداد ماه', 'number', { default: 1, required: true, min: 1, max: 1200 }),
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  {
    key: 'boms',
    title: 'فرمول ساخت',
    singular: 'فرمول ساخت',
    group: 'تولید',
    icon: 'flask',
    description: 'مواد اولیهٔ موردنیاز برای ساخت هر واحد محصول',
    fields: [
      code,
      name,
      f('productId', 'محصول نهایی', 'select', { ref: 'products', required: true }),
      notes,
    ],
    kind: 'invoice',
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'production',
    title: 'سفارش‌های تولید',
    singular: 'سفارش تولید',
    group: 'تولید',
    icon: 'factory',
    description: 'برنامه‌ریزی تولید، مصرف مواد و ورود محصول',
    fields: [
      code,
      f('bomId', 'فرمول ساخت', 'select', { ref: 'boms', required: true }),
      date,
      f('warehouseId', 'انبار', 'select', { ref: 'warehouses', required: true }),
      f('quantity', 'تعداد تولید', 'number', { required: true, min: 1 }),
      f('overhead', 'هزینه سربار', 'money', { default: 0, min: 0 }),
      notes,
    ],
    status: ['پیش‌نویس', 'در حال تولید', 'تکمیل شده', 'لغو شده'],
  },
  {
    key: 'projects',
    title: 'پروژه‌ها',
    singular: 'پروژه',
    group: 'پروژه‌ها',
    icon: 'folder',
    description: 'بودجه، زمان‌بندی و پیشرفت پروژه‌ها',
    fields: [
      code,
      name,
      person,
      f('manager', 'مدیر پروژه'),
      date,
      f('dueDate', 'موعد تحویل', 'date', { required: true }),
      f('budget', 'بودجه', 'money', { required: true, min: 0 }),
      f('progress', 'پیشرفت (%)', 'number', { default: 0, min: 0, max: 100 }),
      notes,
    ],
    status: ['برنامه‌ریزی', 'در حال اجرا', 'تکمیل شده', 'متوقف'],
  },
  {
    key: 'project-costs',
    title: 'هزینه و درآمد پروژه',
    singular: 'تراکنش پروژه',
    group: 'پروژه‌ها',
    icon: 'wallet',
    description: 'کنترل بودجه و سودآوری به تفکیک پروژه',
    fields: [
      code,
      f('projectId', 'پروژه', 'select', { ref: 'projects', required: true }),
      f('name', 'شرح', 'text', { required: true }),
      date,
      f('type', 'نوع', 'select', { options: ['هزینه', 'درآمد'], default: 'هزینه' }),
      amount,
      bank,
      notes,
    ],
    status: ['پیش‌نویس', 'تأیید شده', 'لغو شده'],
  },
  {
    key: 'companies',
    title: 'شرکت‌ها',
    singular: 'شرکت',
    group: 'مدیریت',
    icon: 'building',
    description: 'مدیریت شرکت‌های مستقل در یک فضای کاری',
    global: true,
    admin: true,
    fields: [
      code,
      name,
      f('nationalId', 'شناسه ملی'),
      f('registration', 'شماره ثبت'),
      f('phone', 'تلفن'),
      f('address', 'نشانی', 'textarea'),
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'branches',
    title: 'شعبه‌ها',
    singular: 'شعبه',
    group: 'مدیریت',
    icon: 'network',
    description: 'شعبه‌های شرکت انتخاب‌شده و اطلاعات تماس',
    admin: true,
    fields: [
      code,
      name,
      f('manager', 'مدیر شعبه'),
      f('phone', 'تلفن'),
      f('address', 'نشانی', 'textarea'),
    ],
    status: ['فعال', 'غیرفعال'],
  },
  {
    key: 'fiscal-years',
    title: 'سال‌های مالی',
    singular: 'سال مالی',
    group: 'مدیریت',
    icon: 'calendar',
    description: 'دوره‌های مالی و کنترل ثبت در دوره‌های بسته',
    admin: true,
    fields: [
      name,
      f('startDate', 'از تاریخ', 'date', { required: true }),
      f('endDate', 'تا تاریخ', 'date', { required: true }),
    ],
    status: ['باز', 'بسته'],
  },
  {
    key: 'currencies',
    title: 'ارزها و نرخ تبدیل',
    singular: 'نرخ ارز',
    group: 'مدیریت',
    icon: 'coins',
    description: 'نرخ‌های آزمایشی و قابل‌ویرایش؛ مبنای دفاتر تومان است',
    admin: true,
    fields: [
      f('name', 'ارز', 'select', {
        options: ['تومان', 'ریال', 'دلار', 'یورو', 'درهم'],
        required: true,
      }),
      f('rate', 'معادل یک واحد به تومان', 'number', { required: true, min: 0.000001 }),
      date,
    ],
  },
  {
    key: 'users',
    title: 'کاربران و دسترسی‌ها',
    singular: 'کاربر',
    group: 'مدیریت',
    icon: 'shield',
    description: 'مدیر: دسترسی کامل · حسابدار: عملیات مالی · مشاهده‌گر: فقط خواندن',
    global: true,
    admin: true,
    fields: [
      name,
      f('email', 'ایمیل', 'email', { required: true }),
      f('role', 'نقش', 'select', {
        options: ['مدیر', 'حسابدار', 'مشاهده‌گر'],
        required: true,
        default: 'مشاهده‌گر',
      }),
      f('password', 'رمز عبور (برای تغییر وارد کنید)', 'text', { hidden: true }),
    ],
    status: ['فعال', 'غیرفعال'],
  },
];
export const reports = [
  {
    key: 'profit-loss',
    title: 'سود و زیان',
    description: 'درآمدها، هزینه‌ها و سود خالص دوره',
    icon: 'chart',
  },
  {
    key: 'balance-sheet',
    title: 'ترازنامه',
    description: 'وضعیت دارایی، بدهی و حقوق مالکانه',
    icon: 'scale',
  },
  {
    key: 'trial-balance',
    title: 'تراز آزمایشی',
    description: 'گردش و ماندهٔ بدهکار و بستانکار حساب‌ها',
    icon: 'columns',
  },
  {
    key: 'journal',
    title: 'دفتر روزنامه',
    description: 'تمام ثبت‌های مالی به ترتیب تاریخ',
    icon: 'book',
  },
  { key: 'ledger', title: 'دفتر کل', description: 'گردش تفصیلی هر حساب و ماندهٔ آن', icon: 'book' },
  {
    key: 'receivables',
    title: 'بدهکاران و بستانکاران',
    description: 'ماندهٔ طرف حساب‌ها و مطالبات باز',
    icon: 'users',
  },
  {
    key: 'inventory',
    title: 'موجودی و ارزش انبار',
    description: 'تعداد و ارزش کالا به تفکیک انبار',
    icon: 'warehouse',
  },
  { key: 'cashflow', title: 'جریان نقدی', description: 'ورودی و خروجی وجوه نقد', icon: 'arrows' },
  {
    key: 'tax',
    title: 'مالیات و عوارض',
    description: 'مالیات خرید و فروش بر اساس نرخ ثبت‌شده در فاکتور',
    icon: 'receipt',
  },
  {
    key: 'project-profit',
    title: 'سودآوری پروژه‌ها',
    description: 'مقایسهٔ بودجه، هزینه و درآمد پروژه',
    icon: 'folder',
  },
];
export const moduleByKey = (key: string) => modules.find((m) => m.key === key);
export const masterKeys = new Set([
  'people',
  'products',
  'warehouses',
  'banks',
  'accounts',
  'employees',
  'assets',
  'boms',
  'projects',
  'branches',
  'fiscal-years',
  'currencies',
  'companies',
  'users',
]);
